name: 🚀 Deploy to GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build
        
      - name: Copy .well-known directory and config files to dist
        run: |
          mkdir -p ./dist/.well-known
          cp ./.well-known/assetlinks.json ./dist/.well-known/
          cp .nojekyll ./dist/ || touch ./dist/.nojekyll
          cp _config.yml ./dist/ || echo "include: ['.well-known']" > ./dist/_config.yml
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist